settlus/chain

.dockerignore, .github/workflows/docker.yml, Dockerfile
add docker ci.
builds the Settlus docker image on push to main & tags, and pushes the image to https://ghcr.io/settlus/chain.
=> ci: add docker ci

go.mod, go.sum, tools/interop-node/feeder/block_feeder.go
return `handleprevote()` with an error if fails to send prevote.
updating `feeder.lastPrevote` without actually sending the prevote to Settlus can cause unexpected behaviors.
=> interop-node: return handleprevote with an error if fails to send prevote

.github/workflows/build.yml, .github/workflows/release.yml, .gitignore, .goreleaser.yml, Makefile
- when a new tag is pushed, `release.yml` workflow creates release binaries with different architectures and OSs.
- `release.yml` creates separate binaries for `settlusd` and `interop-node`
- remove archiving binaries from `build.yml`. only archive binaries in a release.
I have tested the release workflow in my forked repo. https://github.com/jacobhjkim/chain/releases/tag/v0.0.11
=> ci: add release workflow

cmd/settlusd/cmd/root.go
This PR enables telemetry support on chain init.
=> chore: enable telemetry on init

cmd/settlusd/config/config.go, tools/interop-node/client/settlus.go, tools/interop-node/cmd/config.go, tools/interop-node/config/config.go, tools/interop-node/feeder/block_feeder.go, tools/interop-node/server/server.go, tools/interop-node/signer/kms.go, tools/interop-node/signer/signer.go, tools/interop-node/types/util.go, tools/interop-node/types/util_test.go, utils/utils.go
derive address from either feeder's private key or aws kms
- during the server's initialization, we derive the feeder's bech32 address from either AWS Kms or private key.
=> interop-node: derive address from either feeder's private key or aws kms

.github/workflows/docker.yml
add patch version to docker image tag. currently our docker image tag only includes the major and the minor version as you can see from this link. https://github.com/settlus/chain/pkgs/container/chain
=> ci: add patch version to docker image tag

tools/interop-node/subscriber/ethereum_subscriber.go
After the websocket disconnects, the latest header information ceases to update.
Instead of implementing a websocket reconnection logic, we have decided to switch to HTTP polling.
=> interop-node: fetch headers via HTTP polling, replace web socket

.github/workflows/codeql.yml
setup go in codeql workflow
codeql was complaining about the go version.
=> ci: setup go in codeql workflow

.github/workflows/release.yml
allow text after release tag
i.e. v1.0, v20.15.10, v1.2.3-hotfix, etc.
=> ci: allow text after release tag

tools/interop-node/client/settlus.go, tools/interop-node/config/config.go
allow interop-node feeder to set fee-payer for oracle transactions.
=> interop-node: add fee-payer config

go.mod, go.sum
- bump settlus/cosmos-sdk from 3 to 4
- allow probono validator delegation only through governance
=> chore(deps): bump settlus/cosmos-sdk from 3 to 4

app/app.go
for `stakingkeeper` we have to use a pointer value.
=> fix: use pointer for staking keeper

evmos/x/erc20/types/erc20.pb.go, tools/interop-node/subscriber/ethereum_subscriber.go
use json rpc instead of go-ethereum client for interop-node.
=> feat(interop-node): use json rpc instead of go-ethereum client

Makefile, tools/interop-node/cmd/root.go, tools/interop-node/cmd/version.go, tools/interop-node/version/version.go
So far, it was hard to tell the current version of the `interop-node` node binary. Wit this new `version` CLI, we can easily tell its version.
- updated Makefile to have build flags for interop-node.
- added `github.com/settlus/chain/tools/interop-node/version` package.
=> feat: add version cli for interop-node

tools/interop-node/subscriber/ethereum_subscriber.go, tools/interop-node/types/ethereum.go
Our current geth version derives block hash via hashing the block header. This is results in a block hash mismatch because the current Ethereum mainnet has new fields like `blobGasUsed` and `excessBlobGas` in the block header. This PR address the issue by directly using the block hash returned via JSON-RPC.
- move ethereum RPC output structs to `types/ethereum.go`.
- manually decode block timestamp with `hexutil`.
- `getBlockHash()` returns blockHash (string) and blockTime (uint64) instead of `Block` object
=> fix(interop-node): fix eth block hash mismatch in interop-node

go.mod, go.sum
To measure ABCI metrics, upgrade to cosmos-sdk v0.46.13-settlus.5
https://github.com/settlus/cosmos-sdk/commit/812d48c4d1e8e944b7701772ec8cfa6dddf49dc5
=> upgrade: cosmos-sdk v0.46.13-settlus.5

app/app.go, x/settlement/abci.go, x/settlement/module.go
To mitigate the scenario where the oracle's end vote height is the same as the settlement payout block height
=> fix: move settlement process from beginblock to endblock

tools/interop-node/subscriber/ethereum_subscriber.go, types/hex_address.go, types/hex_address_test.go, types/nft.go, x/oracle/types/vote_data.go, x/oracle/types/vote_data_test.go, x/oracle/voteprocessor/voteprocessor_test.go, x/settlement/keeper/keeper.go, x/settlement/keeper/msg_server.go, x/settlement/keeper/utxr.go, x/settlement/types/recipient.go
Currently, votes with data "0x0" and "0x000" are treated as different. To fix this, we need to normalize the hexaddrstring  to a consistent address length.
=> fix: normalize hexaddrstring for consistency

app/keepers.go, app/keys.go, x/oracle/abci.go, x/oracle/keeper/keeper.go, x/oracle/types/keys.go
TransientStore was not successful for storing current round info.  
KVStore should be the valid option.
=> fix: use KVStore for storing curren round info

config.yml, go.mod, go.sum, tests/e2e/e2e_bank_test.go, tests/e2e/e2e_exec_test.go, tests/e2e/e2e_settlement_test.go, tests/e2e/e2e_setup_test.go, tests/e2e/query.go, types/nft.go
Fix e2e tests
We need to use a specific version of `stretchr/testify` to include this PR (https://github.com/stretchr/testify/pull/1481). Without it, `EventuallyWithT` does not work well with `require`.
`EventuallyWithT` is preferable to plain `Eventually` because it shows exactly which condition is not met. For example, `Eventually`'s error looks like this:
```shell
Error:      	Condition never satisfied
```
In contrast, `EventuallyWithT`'s error log is more informative:
```shell
e2e_settlement_test.go:199:
Error Trace:	/Users/jacob/work/chain/tests/e2e/e2e_settlement_test.go:199
/opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/asm_arm64.s:1222
Error:      	Not equal:
expected: 3
actual  : 2
Test:       	TestIntegrationTestSuite/TestMintableContractTenant/create_new_tenant
```
=> test: fix e2e tests

.github/workflows/build.yml, .github/workflows/codeql.yml, .github/workflows/proto.yml, .github/workflows/release.yml
bump go version to 1.22 in github worflows
=> feat: bump go version to 1.22 in github worflows

tools/interop-node/client/settlus.go, x/oracle/abci.go, x/oracle/keeper/integration_test.go, x/oracle/keeper/keeper.go, x/oracle/module.go
The `interop-node` uses the next height to calculate roundInfo, whereas the chain node returns roundInfo for the current height. To resolve this conflict, update the roundInfo for the next height in the `EndBlocker`.
=> oracle: fix round info bug

tools/interop-node/README.md, x/oracle/README.md
update docs for `interop-node` and `x/oracle`.
- replace docs about interop-node's db with in-memory cache.
- add more info about `RoundInfo` in `x/oracle` docs.
=> docs: update docs for interop-node and x/oracle

Makefile
- update makefile to include ldflags in release CI.
- add `make help` for QoL improvements.
=> ci: update makefile to include ldflags in release ci

go.mod, go.sum
=> hotfix: bump evmos version to v19.0.0-settlus.4

go.mod, go.sum
- https://github.com/evmos/evmos/releases/tag/v19.1.0
=> hotfix: bump evmos version to v19.0.0-settlus.5
